### ISSUE TITLE
Demande de mise à jour

### ISSUE THREAD

**Issue by defts** [tsunammis/graphql-the-new-age-of-api#1]
Hello, 

est-ce que tu penses mettre à jour ce repo avec la prez faite à Lille le 1er mars ? 

Merci d'avance ! 
David.

**Comment by tsunammis** [comment]
@defts Oui, je vais mettre ça à jour d'ici quelques jours ;-)

**Comment by tsunammis** [comment]
@defts Voila :) le repo vient d'être MAJ.

**Comment by defts** [comment]
Merci ! 👍
